-- Config authority model:
-- - universal_fields.name is the canonical key
-- - component fields must reference universal fields
-- - renames are coordinated via rename_universal_field() and cascade automatically

CREATE TABLE IF NOT EXISTS public.config_categories (
  name TEXT PRIMARY KEY,
  category_order INTEGER NOT NULL DEFAULT 100,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.config_categories
  ADD COLUMN IF NOT EXISTS category_order INTEGER;

UPDATE public.config_categories
SET category_order = 100
WHERE category_order IS NULL;

ALTER TABLE public.config_categories
  ALTER COLUMN category_order SET DEFAULT 100;

ALTER TABLE public.config_categories
  ALTER COLUMN category_order SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'config_categories_category_order_check'
      AND conrelid = 'public.config_categories'::regclass
  ) THEN
    ALTER TABLE public.config_categories
      ADD CONSTRAINT config_categories_category_order_check
      CHECK (category_order >= 0);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.universal_fields (
  name TEXT PRIMARY KEY,
  category_name TEXT NOT NULL REFERENCES public.config_categories(name) ON UPDATE CASCADE ON DELETE RESTRICT,
  input_type TEXT NOT NULL,
  field_order INTEGER NOT NULL DEFAULT 100,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT universal_fields_input_type_check CHECK (
    input_type IN (
      'text',
      'textarea',
      'number',
      'checkbox',
      'select',
      'json',
      'list',
      'audio_selector',
      'audio_list',
      'audio_prompt',
      'blanks_mapper',
      'audio_lines_mapper',
      'choice_elements_mapper',
      'match_pairs_mapper',
      'avatar_dialogues_mapper',
      'media_picker'
    )
  ),
  CONSTRAINT universal_fields_field_order_check CHECK (field_order >= 0)
);

ALTER TABLE public.universal_fields
  ADD COLUMN IF NOT EXISTS field_order INTEGER;

UPDATE public.universal_fields
SET field_order = 100
WHERE field_order IS NULL;

ALTER TABLE public.universal_fields
  ALTER COLUMN field_order SET DEFAULT 100;

ALTER TABLE public.universal_fields
  ALTER COLUMN field_order SET NOT NULL;

ALTER TABLE public.universal_fields
  DROP CONSTRAINT IF EXISTS universal_fields_input_type_check;

ALTER TABLE public.universal_fields
  ADD CONSTRAINT universal_fields_input_type_check
  CHECK (
    input_type IN (
      'text',
      'textarea',
      'number',
      'checkbox',
      'select',
      'json',
      'list',
      'audio_selector',
      'audio_list',
      'audio_prompt',
      'blanks_mapper',
      'audio_lines_mapper',
      'choice_elements_mapper',
      'match_pairs_mapper',
      'avatar_dialogues_mapper',
      'media_picker'
    )
  );

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'universal_fields_field_order_check'
      AND conrelid = 'public.universal_fields'::regclass
  ) THEN
    ALTER TABLE public.universal_fields
      ADD CONSTRAINT universal_fields_field_order_check
      CHECK (field_order >= 0);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'universal_fields_category_name_name_key'
      AND conrelid = 'public.universal_fields'::regclass
  ) THEN
    ALTER TABLE public.universal_fields
      ADD CONSTRAINT universal_fields_category_name_name_key UNIQUE (category_name, name);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.component_config_fields (
  component_name TEXT NOT NULL,
  category_name TEXT NOT NULL,
  field_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (component_name, category_name, field_name)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'component_config_fields_category_fk'
      AND conrelid = 'public.component_config_fields'::regclass
  ) THEN
    ALTER TABLE public.component_config_fields
      ADD CONSTRAINT component_config_fields_category_fk
      FOREIGN KEY (category_name)
      REFERENCES public.config_categories(name)
      ON UPDATE CASCADE
      ON DELETE RESTRICT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'component_config_fields_field_fk'
      AND conrelid = 'public.component_config_fields'::regclass
  ) THEN
    ALTER TABLE public.component_config_fields
      ADD CONSTRAINT component_config_fields_field_fk
      FOREIGN KEY (category_name, field_name)
      REFERENCES public.universal_fields(category_name, name)
      ON UPDATE CASCADE
      ON DELETE RESTRICT;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.universal_field_rename_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  old_name TEXT NOT NULL,
  new_name TEXT NOT NULL,
  renamed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE VIEW public.config_universal_fields AS
SELECT
  uf.category_name,
  uf.name AS field_name,
  uf.input_type,
  uf.field_order,
  cc.category_order,
  fd.select_options_json,
  fd.select_source,
  fd.is_read_only
FROM public.universal_fields uf
JOIN public.config_categories cc
  ON cc.name = uf.category_name
LEFT JOIN public.field_dictionary fd
  ON fd.field_key = uf.name;

CREATE OR REPLACE VIEW public.config_component_fields AS
SELECT
  ccf.component_name,
  ccf.category_name,
  ccf.field_name,
  uf.input_type,
  uf.field_order,
  cc.category_order,
  fd.select_options_json,
  fd.select_source,
  fd.is_read_only
FROM public.component_config_fields ccf
JOIN public.universal_fields uf
  ON uf.category_name = ccf.category_name
 AND uf.name = ccf.field_name
JOIN public.config_categories cc
  ON cc.name = ccf.category_name
LEFT JOIN public.field_dictionary fd
  ON fd.field_key = ccf.field_name;

CREATE OR REPLACE FUNCTION public.rename_universal_field(old_name TEXT, new_name TEXT)
RETURNS TABLE(category_name TEXT, name TEXT, input_type TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF old_name IS NULL OR btrim(old_name) = '' THEN
    RAISE EXCEPTION 'old_name cannot be empty';
  END IF;

  IF new_name IS NULL OR btrim(new_name) = '' THEN
    RAISE EXCEPTION 'new_name cannot be empty';
  END IF;

  IF old_name = new_name THEN
    RAISE EXCEPTION 'old_name and new_name must be different';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.universal_fields uf
    WHERE uf.name = old_name
  ) THEN
    RAISE EXCEPTION 'Universal field "%" does not exist', old_name;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.universal_fields uf
    WHERE uf.name = new_name
  ) THEN
    RAISE EXCEPTION 'Universal field "%" already exists', new_name;
  END IF;

  RETURN QUERY
  UPDATE public.universal_fields uf
  SET name = new_name
  WHERE uf.name = old_name
  RETURNING uf.category_name, uf.name, uf.input_type;

  INSERT INTO public.universal_field_rename_audit (old_name, new_name)
  VALUES (old_name, new_name);
END;
$$;

REVOKE ALL ON FUNCTION public.rename_universal_field(TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rename_universal_field(TEXT, TEXT) TO service_role;

CREATE OR REPLACE FUNCTION public.set_universal_field_order(p_category_name TEXT, p_field_name TEXT, p_field_order INTEGER)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_category_name IS NULL OR btrim(p_category_name) = '' THEN
    RAISE EXCEPTION 'p_category_name cannot be empty';
  END IF;

  IF p_field_name IS NULL OR btrim(p_field_name) = '' THEN
    RAISE EXCEPTION 'p_field_name cannot be empty';
  END IF;

  IF p_field_order IS NULL OR p_field_order < 0 THEN
    RAISE EXCEPTION 'p_field_order must be >= 0';
  END IF;

  UPDATE public.universal_fields uf
  SET field_order = p_field_order
  WHERE uf.category_name = p_category_name
    AND uf.name = p_field_name;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Universal field "%.%" does not exist', p_category_name, p_field_name;
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.set_universal_field_order(TEXT, TEXT, INTEGER) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.set_universal_field_order(TEXT, TEXT, INTEGER) TO service_role;

CREATE OR REPLACE FUNCTION public.set_component_config_field_enabled(
  p_component_name TEXT,
  p_category_name TEXT,
  p_field_name TEXT,
  p_enabled BOOLEAN
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_component_name IS NULL OR btrim(p_component_name) = '' THEN
    RAISE EXCEPTION 'p_component_name cannot be empty';
  END IF;

  IF p_category_name IS NULL OR btrim(p_category_name) = '' THEN
    RAISE EXCEPTION 'p_category_name cannot be empty';
  END IF;

  IF p_field_name IS NULL OR btrim(p_field_name) = '' THEN
    RAISE EXCEPTION 'p_field_name cannot be empty';
  END IF;

  IF p_enabled THEN
    INSERT INTO public.component_config_fields (component_name, category_name, field_name)
    VALUES (p_component_name, p_category_name, p_field_name)
    ON CONFLICT (component_name, category_name, field_name) DO NOTHING;
  ELSE
    DELETE FROM public.component_config_fields
    WHERE component_name = p_component_name
      AND category_name = p_category_name
      AND field_name = p_field_name;
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.set_component_config_field_enabled(TEXT, TEXT, TEXT, BOOLEAN) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.set_component_config_field_enabled(TEXT, TEXT, TEXT, BOOLEAN) TO service_role;

GRANT SELECT ON public.config_universal_fields TO anon, authenticated;
GRANT SELECT ON public.config_component_fields TO anon, authenticated;

INSERT INTO public.config_categories (name, category_order)
VALUES
  ('Identity & Lifecycle', 1),
  ('Purpose & Outcomes', 2),
  ('Scope, Prerequisites & Targeting', 3),
  ('Content & Media', 4),
  ('Instructions & Flow', 5),
  ('Pedagogy & Scaffolding', 6),
  ('Assessment & Mastery', 7),
  ('Structure & Sequencing', 8),
  ('Localization', 9),
  ('Teacher Guidance', 10),
  ('AI Generation & Prompting', 11),
  ('Activities & Interaction', 12),
  ('Links, Dependencies & Summaries', 13),
  ('Telemetry & Analytics', 14),
  ('Operations, Provenance & Governance', 15)
ON CONFLICT (name) DO UPDATE
SET category_order = EXCLUDED.category_order;

UPDATE public.universal_fields
SET category_name = 'Identity & Lifecycle'
WHERE category_name = 'category';

UPDATE public.component_config_fields
SET category_name = 'Identity & Lifecycle'
WHERE category_name = 'category';

DELETE FROM public.component_config_fields
WHERE field_name IN ('ingestSource', 'lastUpdatedAt', 'lastUpdatedBy', 'ownerTeam', 'version');

DELETE FROM public.universal_fields
WHERE name IN ('ingestSource', 'lastUpdatedAt', 'lastUpdatedBy', 'ownerTeam', 'version');

INSERT INTO public.universal_fields (name, category_name, input_type, field_order)
VALUES
  ('id', 'Identity & Lifecycle', 'text', 1),
  ('title', 'Identity & Lifecycle', 'text', 2),
  ('level', 'Identity & Lifecycle', 'text', 3),
  ('text', 'Identity & Lifecycle', 'text', 4),
  ('subtitle', 'Identity & Lifecycle', 'text', 5)
ON CONFLICT (name) DO UPDATE
SET
  category_name = EXCLUDED.category_name,
  input_type = EXCLUDED.input_type,
  field_order = EXCLUDED.field_order;

SELECT public.set_component_config_field_enabled('modules', 'Identity & Lifecycle', 'id', true);
SELECT public.set_component_config_field_enabled('modules', 'Identity & Lifecycle', 'title', true);
SELECT public.set_component_config_field_enabled('modules', 'Identity & Lifecycle', 'level', true);
SELECT public.set_component_config_field_enabled('modules', 'Identity & Lifecycle', 'text', true);
SELECT public.set_component_config_field_enabled('modules', 'Identity & Lifecycle', 'subtitle', false);

DELETE FROM public.config_categories cc
WHERE cc.name NOT IN (
    'Identity & Lifecycle',
    'Purpose & Outcomes',
    'Scope, Prerequisites & Targeting',
    'Content & Media',
    'Instructions & Flow',
    'Pedagogy & Scaffolding',
    'Assessment & Mastery',
    'Structure & Sequencing',
    'Localization',
    'Teacher Guidance',
    'AI Generation & Prompting',
    'Activities & Interaction',
    'Links, Dependencies & Summaries',
    'Telemetry & Analytics',
    'Operations, Provenance & Governance'
  )
  AND NOT EXISTS (
    SELECT 1 FROM public.universal_fields uf WHERE uf.category_name = cc.name
  )
  AND NOT EXISTS (
    SELECT 1 FROM public.component_config_fields ccf WHERE ccf.category_name = cc.name
  )
  AND NOT EXISTS (
    SELECT 1 FROM public.field_dictionary fd WHERE fd.category_name = cc.name
  );
