-- 012_component_activation_seed.sql
-- Purpose: make component activation deterministic and reproducible from migration chain.
-- Source: live local authority state on 2026-04-07.
-- Idempotent: safe to re-run.

DELETE FROM public.component_config_fields;
DELETE FROM public.field_dictionary_component_rules;

INSERT INTO public.field_dictionary_component_rules (field_key, component_name, is_present, is_required)
VALUES
  ('activityTypes', 'groups', true, false),
  ('aiInstructions', 'groups', true, false),
  ('allowRetry', 'groups', true, false),
  ('allowSkip', 'groups', true, false),
  ('anecdoteOrMemoryHook', 'groups', true, false),
  ('assessmentPlan', 'groups', true, false),
  ('audienceNotes', 'groups', true, false),
  ('autoAdvance', 'groups', true, false),
  ('levelMax', 'groups', true, false),
  ('levelMin', 'groups', true, false),
  ('breakingChangeGuard', 'groups', true, false),
  ('canonicalNodeKey', 'groups', true, false),
  ('cefrLevel', 'groups', true, false),
  ('cefrMax', 'groups', true, false),
  ('cefrMin', 'groups', true, false),
  ('changeImpactAssessment', 'groups', true, false),
  ('commonMisconceptions', 'groups', true, false),
  ('competencyTags', 'groups', true, false),
  ('culturalContext', 'groups', true, false),
  ('defaultLang', 'groups', true, false),
  ('description', 'groups', true, false),
  ('diagnosticChecks', 'groups', true, false),
  ('differentiationPaths', 'groups', true, false),
  ('differentiationStrategies', 'groups', true, false),
  ('diffLog', 'groups', true, false),
  ('discourseFocus', 'groups', true, false),
  ('estimatedMinutes', 'groups', true, false),
  ('exampleResponses', 'groups', true, false),
  ('expansionGuidelines', 'groups', true, false),
  ('expectedCompletionRate', 'groups', true, false),
  ('expectedTimeOnTask', 'groups', true, false),
  ('experimentFlag', 'groups', true, false),
  ('extractabilityTier', 'groups', true, false),
  ('extraPracticeNotes', 'groups', true, false),
  ('forbiddenPatterns', 'groups', true, false),
  ('grammarFocus', 'groups', true, false),
  ('groupGoal', 'groups', true, false),
  ('groupId', 'groups', true, false),
  ('groupName', 'groups', true, false),
  ('groupPlan', 'groups', true, false),
  ('groupSlidesPlan', 'groups', true, false),
  ('groupSummary', 'groups', true, false),
  ('groupType', 'groups', true, false),
  ('ingestPayload', 'groups', true, false),
  ('ingestSource', 'groups', true, false),
  ('isRequiredToPass', 'groups', true, false),
  ('keywords', 'groups', true, false),
  ('l1InterferenceNotes', 'groups', true, false),
  ('lastUpdatedAt', 'groups', true, false),
  ('lastUpdatedBy', 'groups', true, false),
  ('learningGoalPreviewGroup', 'groups', true, false),
  ('learningObjectives', 'groups', true, false),
  ('lessonId', 'groups', true, false),
  ('level', 'groups', true, false),
  ('linkedGroups', 'groups', true, false),
  ('linkedResources', 'groups', true, false),
  ('manualOverrideJson', 'groups', true, false),
  ('masteryRule', 'groups', true, false),
  ('masteryThreshold', 'groups', true, false),
  ('maxAttempts', 'groups', true, false),
  ('maxScoreValue', 'groups', true, false),
  ('metadata', 'groups', true, false),
  ('minAttemptsBeforeSkip', 'groups', true, false),
  ('moduleId', 'groups', true, false),
  ('slug', 'groups', true, true),
  ('notesForTeacherOrAI', 'groups', true, false),
  ('orderIndex', 'groups', true, false),
  ('ownerTeam', 'groups', true, false),
  ('pacingNotes', 'groups', true, false),
  ('passingScoreType', 'groups', true, false),
  ('passingScoreValue', 'groups', true, false),
  ('passRequiredForNext', 'groups', true, false),
  ('prerequisiteEdges', 'groups', true, false),
  ('prerequisiteNodes', 'groups', true, false),
  ('prerequisites', 'groups', true, false),
  ('prerequisiteSlices', 'groups', true, false),
  ('pronunciationFocus', 'groups', true, false),
  ('publishNotes', 'groups', true, false),
  ('purposeRelationshipTag', 'groups', true, false),
  ('registerTone', 'groups', true, false),
  ('registerVariants', 'groups', true, false),
  ('remediationGuidance', 'groups', true, false),
  ('remediationPaths', 'groups', true, false),
  ('requiredScore', 'groups', true, false),
  ('retryPolicy', 'groups', true, false),
  ('reviewRequired', 'groups', true, false),
  ('shortSummaryTeacherGroup', 'groups', true, false),
  ('signatureMetaphors', 'groups', true, false),
  ('simplificationGuidelines', 'groups', true, false),
  ('skipPolicy', 'groups', true, false),
  ('slidePlan', 'groups', true, false),
  ('sourceVersion', 'groups', true, false),
  ('styleConstraints', 'groups', true, false),
  ('successCriteria', 'groups', true, false),
  ('tags', 'groups', true, false),
  ('targetedEdges', 'groups', true, false),
  ('targetedNodes', 'groups', true, false),
  ('targetedSlices', 'groups', true, false),
  ('targetLanguage', 'groups', true, false),
  ('targetNodeKeys', 'groups', true, false),
  ('teacherNotes', 'groups', true, false),
  ('teacherOverview', 'groups', true, false),
  ('telemetryTags', 'groups', true, false),
  ('timeExpectationGroup', 'groups', true, false),
  ('title', 'groups', true, false),
  ('topicCategory', 'groups', true, false),
  ('version', 'groups', true, false),
  ('visibility', 'groups', true, false),
  ('vocabularyTheme', 'groups', true, false),
  ('activityDescription', 'lessons', true, false),
  ('activityTypes', 'lessons', true, false),
  ('aiInstructions', 'lessons', true, false),
  ('allowRetry', 'lessons', true, false),
  ('allowSkip', 'lessons', true, false),
  ('assessmentPlan', 'lessons', true, false),
  ('audienceNotes', 'lessons', true, false),
  ('levelMax', 'lessons', true, false),
  ('levelMin', 'lessons', true, false),
  ('breakingChangeGuard', 'lessons', true, false),
  ('canonicalNodeKey', 'lessons', true, false),
  ('cefrLevel', 'lessons', true, false),
  ('cefrMax', 'lessons', true, false),
  ('cefrMin', 'lessons', true, false),
  ('changeImpactAssessment', 'lessons', true, false),
  ('commonMisconceptions', 'lessons', true, false),
  ('competencyTags', 'lessons', true, false),
  ('coreTopics', 'lessons', true, false),
  ('culturalContext', 'lessons', true, false),
  ('defaultLang', 'lessons', true, false),
  ('description', 'lessons', true, false),
  ('diagnosticChecks', 'lessons', true, false),
  ('differentiationPaths', 'lessons', true, false),
  ('differentiationStrategies', 'lessons', true, false),
  ('diffLog', 'lessons', true, false),
  ('discourseFocus', 'lessons', true, false),
  ('estimatedMinutes', 'lessons', true, false),
  ('exampleResponses', 'lessons', true, false),
  ('expansionGuidelines', 'lessons', true, false),
  ('expectedCompletionRate', 'lessons', true, false),
  ('expectedTimeOnTask', 'lessons', true, false),
  ('experimentFlag', 'lessons', true, false),
  ('extraPracticeNotes', 'lessons', true, false),
  ('forbiddenPatterns', 'lessons', true, false),
  ('grammarFocus', 'lessons', true, false),
  ('groupPlan', 'lessons', true, false),
  ('ingestPayload', 'lessons', true, false),
  ('ingestSource', 'lessons', true, false),
  ('keyTakeawaysLesson', 'lessons', true, false),
  ('keywords', 'lessons', true, false),
  ('l1InterferenceNotes', 'lessons', true, false),
  ('lastUpdatedAt', 'lessons', true, false),
  ('lastUpdatedBy', 'lessons', true, false),
  ('learningGoalPreviewLesson', 'lessons', true, false),
  ('learningObjectives', 'lessons', true, false),
  ('lessonId', 'lessons', true, false),
  ('level', 'lessons', true, false),
  ('linkedResources', 'lessons', true, false),
  ('manualOverrideJson', 'lessons', true, false),
  ('masteryRule', 'lessons', true, false),
  ('masteryThreshold', 'lessons', true, false),
  ('maxAttempts', 'lessons', true, false),
  ('minAttemptsBeforeSkip', 'lessons', true, false),
  ('moduleId', 'lessons', true, false),
  ('slug', 'lessons', true, true),
  ('notesForTeacherOrAI', 'lessons', true, false),
  ('orderIndex', 'lessons', true, false),
  ('ownerTeam', 'lessons', true, false),
  ('pacingNotes', 'lessons', true, false),
  ('passRequiredForNext', 'lessons', true, false),
  ('pedagogicalStrategy', 'lessons', true, false),
  ('practiceProgression', 'lessons', true, false),
  ('prerequisiteEdges', 'lessons', true, false),
  ('prerequisiteNodes', 'lessons', true, false),
  ('prerequisites', 'lessons', true, false),
  ('prerequisiteSlices', 'lessons', true, false),
  ('priorLessons', 'lessons', true, false),
  ('pronunciationFocus', 'lessons', true, false),
  ('publishNotes', 'lessons', true, false),
  ('registerTone', 'lessons', true, false),
  ('registerVariants', 'lessons', true, false),
  ('remediationGuidance', 'lessons', true, false),
  ('remediationPaths', 'lessons', true, false),
  ('requiredScore', 'lessons', true, false),
  ('retryPolicy', 'lessons', true, false),
  ('reviewRequired', 'lessons', true, false),
  ('scaffoldingPlan', 'lessons', true, false),
  ('shortSummaryLessonAdmin', 'lessons', true, false),
  ('shortSummaryLessonStudent', 'lessons', true, false),
  ('shortSummaryTeacherLesson', 'lessons', true, false),
  ('signatureMetaphors', 'lessons', true, false),
  ('simplificationGuidelines', 'lessons', true, false),
  ('skipPolicy', 'lessons', true, false),
  ('slidePlan', 'lessons', true, false),
  ('sourceVersion', 'lessons', true, false),
  ('styleConstraints', 'lessons', true, false),
  ('successCriteria', 'lessons', true, false),
  ('tags', 'lessons', true, false),
  ('targetedEdges', 'lessons', true, false),
  ('targetedNodes', 'lessons', true, false),
  ('targetedSlices', 'lessons', true, false),
  ('targetLanguage', 'lessons', true, false),
  ('targetNodeKeys', 'lessons', true, false),
  ('teacherNotes', 'lessons', true, false),
  ('teacherOverview', 'lessons', true, false),
  ('telemetryTags', 'lessons', true, false),
  ('timeExpectationLesson', 'lessons', true, false),
  ('title', 'lessons', true, false),
  ('topicCategory', 'lessons', true, false),
  ('version', 'lessons', true, false),
  ('visibility', 'lessons', true, false),
  ('vocabularyTheme', 'lessons', true, false),
  ('aiInstructions', 'modules', true, false),
  ('audienceNotes', 'modules', true, false),
  ('authorNotes', 'modules', true, false),
  ('levelMax', 'modules', true, false),
  ('levelMin', 'modules', true, false),
  ('breakingChangeGuard', 'modules', true, false),
  ('canonicalNodeKey', 'modules', true, false),
  ('capstoneLesson', 'modules', true, false),
  ('cefrMax', 'modules', true, false),
  ('cefrMin', 'modules', true, false),
  ('changeImpactAssessment', 'modules', true, false),
  ('commonMisconceptions', 'modules', true, false),
  ('competencyTags', 'modules', true, false),
  ('coreTopics', 'modules', true, false),
  ('defaultLang', 'modules', true, false),
  ('description', 'modules', true, false),
  ('differentiationPaths', 'modules', true, false),
  ('differentiationStrategies', 'modules', true, false),
  ('diffLog', 'modules', true, false),
  ('discourseFocus', 'modules', true, false),
  ('expansionGuidelines', 'modules', true, false),
  ('expectedCompletionRate', 'modules', true, false),
  ('expectedModuleDurationMinutes', 'modules', true, false),
  ('experimentFlag', 'modules', true, false),
  ('forbiddenPatterns', 'modules', true, false),
  ('grammarFocus', 'modules', true, false),
  ('ingestPayload', 'modules', true, false),
  ('ingestSource', 'modules', true, false),
  ('keywords', 'modules', true, false),
  ('lastUpdatedAt', 'modules', true, false),
  ('lastUpdatedBy', 'modules', true, false),
  ('learningGoalPreviewModule', 'modules', true, false),
  ('learningObjectives', 'modules', true, false),
  ('lessonSequenceRules', 'modules', true, false),
  ('level', 'modules', true, true),
  ('linkedModules', 'modules', true, false),
  ('linkedResources', 'modules', true, false),
  ('manualOverrideJson', 'modules', true, false),
  ('metadata', 'modules', true, false),
  ('moduleAssessmentPlan', 'modules', true, false),
  ('moduleGoal', 'modules', true, false),
  ('moduleId', 'modules', true, false),
  ('slug', 'modules', true, true),
  ('moduleMasteryRule', 'modules', true, false),
  ('moduleMasteryThreshold', 'modules', true, false),
  ('moduleOutcomes', 'modules', true, false),
  ('optionalLessons', 'modules', true, false),
  ('orderIndex', 'modules', true, false),
  ('ownerTeam', 'modules', true, false),
  ('pedagogicalStrategy', 'modules', true, false),
  ('prerequisiteModules', 'modules', true, false),
  ('progressionNotes', 'modules', true, false),
  ('pronunciationFocus', 'modules', true, false),
  ('publishNotes', 'modules', true, false),
  ('registerTone', 'modules', true, false),
  ('remediationGuidance', 'modules', true, false),
  ('remediationPaths', 'modules', true, false),
  ('requiredLessons', 'modules', true, false),
  ('reviewRequired', 'modules', true, false),
  ('sequenceType', 'modules', true, false),
  ('shortSummaryTeacherModule', 'modules', true, false),
  ('simplificationGuidelines', 'modules', true, false),
  ('sourceVersion', 'modules', true, false),
  ('styleConstraints', 'modules', true, false),
  ('tags', 'modules', true, false),
  ('targetLanguage', 'modules', true, false),
  ('teacherNotes', 'modules', true, false),
  ('teacherOverview', 'modules', true, false),
  ('telemetryTags', 'modules', true, false),
  ('title', 'modules', true, false),
  ('topicCategory', 'modules', true, false),
  ('version', 'modules', true, false),
  ('visibility', 'modules', true, false),
  ('vocabularyTheme', 'modules', true, false),
  ('aiInstructions', 'slides', true, false),
  ('anecdoteOrMemoryHook', 'slides', true, false),
  ('assessmentPlan', 'slides', true, false),
  ('audioId', 'slides', true, false),
  ('body1', 'slides', true, false),
  ('body2', 'slides', true, false),
  ('body3', 'slides', true, false),
  ('body4', 'slides', true, false),
  ('body5', 'slides', true, false),
  ('body6', 'slides', true, false),
  ('body7', 'slides', true, false),
  ('body8', 'slides', true, false),
  ('buttons', 'slides', true, false),
  ('commonMisconceptions', 'slides', true, false),
  ('culturalContext', 'slides', true, false),
  ('defaultLang', 'slides', true, false),
  ('description', 'slides', true, false),
  ('differentiationPaths', 'slides', true, false),
  ('diffLog', 'slides', true, false),
  ('expansionGuidelines', 'slides', true, false),
  ('extraPracticeNotes', 'slides', true, false),
  ('forbiddenPatterns', 'slides', true, false),
  ('groupId', 'slides', true, false),
  ('groupName', 'slides', true, false),
  ('ingestPayload', 'slides', true, false),
  ('ingestSource', 'slides', true, false),
  ('instructions', 'slides', true, false),
  ('keyTakeawaysSlide', 'slides', true, false),
  ('l1InterferenceNotes', 'slides', true, false),
  ('lastUpdatedAt', 'slides', true, false),
  ('lastUpdatedBy', 'slides', true, false),
  ('learningObjectives', 'slides', true, false),
  ('lessonId', 'slides', true, false),
  ('metadata', 'slides', true, false),
  ('moduleId', 'slides', true, false),
  ('notesForTeacherOrAI', 'slides', true, false),
  ('orderIndex', 'slides', true, false),
  ('ownerTeam', 'slides', true, false),
  ('registerVariants', 'slides', true, false),
  ('remediationPaths', 'slides', true, false),
  ('shortSummaryTeacherSlide', 'slides', true, false),
  ('signatureMetaphors', 'slides', true, false),
  ('simplificationGuidelines', 'slides', true, false),
  ('slideId', 'slides', true, true),
  ('slug', 'slides', true, true),
  ('sourceVersion', 'slides', true, false),
  ('styleConstraints', 'slides', true, false),
  ('successCriteria', 'slides', true, false),
  ('tags', 'slides', true, false),
  ('targetLanguage', 'slides', true, false),
  ('targetNodeKeys', 'slides', true, false),
  ('teacherNotes', 'slides', true, false),
  ('teacherOverview', 'slides', true, false),
  ('telemetryTags', 'slides', true, false),
  ('textSubtype', 'slides', true, false),
  ('type', 'slides', true, false),
  ('version', 'slides', true, false),
  ('visibility', 'slides', true, false);

INSERT INTO public.field_dictionary_component_rules (field_key, component_name, is_present, is_required)
VALUES
  ('audioId', 'title_slides', true, false),
  ('buttons', 'title_slides', true, false),
  ('defaultLang', 'title_slides', true, false),
  ('description', 'title_slides', true, false),
  ('diffLog', 'title_slides', true, false),
  ('ingestPayload', 'title_slides', true, false),
  ('ingestSource', 'title_slides', true, false),
  ('instructions', 'title_slides', true, false),
  ('lastUpdatedAt', 'title_slides', true, false),
  ('lastUpdatedBy', 'title_slides', true, false),
  ('lessonId', 'title_slides', true, false),
  ('metadata', 'title_slides', true, false),
  ('moduleId', 'title_slides', true, false),
  ('ownerTeam', 'title_slides', true, false),
  ('primaryCtaAction', 'title_slides', true, false),
  ('primaryCtaLabel', 'title_slides', true, false),
  ('slideId', 'title_slides', true, true),
  ('slug', 'title_slides', true, true),
  ('sourceVersion', 'title_slides', true, false),
  ('subtitle', 'title_slides', true, false),
  ('tags', 'title_slides', true, false),
  ('targetLanguage', 'title_slides', true, false),
  ('title', 'title_slides', true, false),
  ('version', 'title_slides', true, false),
  ('visibility', 'title_slides', true, false);

INSERT INTO public.field_dictionary_component_rules (field_key, component_name, is_present, is_required)
VALUES
  ('activityId', 'lesson_ends', true, false),
  ('audioId', 'lesson_ends', true, false),
  ('buttons', 'lesson_ends', true, false),
  ('defaultLang', 'lesson_ends', true, false),
  ('diffLog', 'lesson_ends', true, false),
  ('extraPracticeNotes', 'lesson_ends', true, false),
  ('groupId', 'lesson_ends', true, false),
  ('groupName', 'lesson_ends', true, false),
  ('ingestPayload', 'lesson_ends', true, false),
  ('ingestSource', 'lesson_ends', true, false),
  ('lastUpdatedAt', 'lesson_ends', true, false),
  ('lastUpdatedBy', 'lesson_ends', true, false),
  ('lessonEndActions', 'lesson_ends', true, false),
  ('lessonEndMessage', 'lesson_ends', true, false),
  ('lessonId', 'lesson_ends', true, true),
  ('metadata', 'lesson_ends', true, false),
  ('moduleId', 'lesson_ends', true, true),
  ('orderIndex', 'lesson_ends', true, true),
  ('ownerTeam', 'lesson_ends', true, false),
  ('recommendedNextStep', 'lesson_ends', true, false),
  ('slideId', 'lesson_ends', true, true),
  ('slug', 'lesson_ends', true, true),
  ('sourceVersion', 'lesson_ends', true, false),
  ('targetLanguage', 'lesson_ends', true, false),
  ('telemetryTags', 'lesson_ends', true, false),
  ('version', 'lesson_ends', true, false),
  ('visibility', 'lesson_ends', true, false);

-- Seed activity slide activation with shared default + ACT profile keys.
WITH activity_slide_default_fields(field_key) AS (
  SELECT UNNEST(
    ARRAY[
      'activityId',
      'acceptedCorrections',
      'aiInstructions',
      'allowRetry',
      'allowSkip',
      'anecdoteOrMemoryHook',
      'assessmentPlan',
      'audienceNotes',
      'audioA',
      'audioB',
      'audioClips',
      'audioId',
      'audioPrompt',
      'autoAdvance',
      'avatarDialogues',
      'levelMax',
      'levelMin',
      'body',
      'blanks',
      'buttons',
      'categoryLabels',
      'cefrLevel',
      'cefrMax',
      'cefrMin',
      'choiceElements',
      'commonMisconceptions',
      'competencyTags',
      'correctAnswer',
      'correctCurveId',
      'correctOddIndex',
      'correctOrderClips',
      'correctOrderWords',
      'correctStressIndex',
      'coreTopics',
      'culturalContext',
      'defaultLang',
      'delayMs',
      'description',
      'diagnosticChecks',
      'differentiationPaths',
      'differentiationStrategies',
      'diffLog',
      'discourseFocus',
      'estimatedMinutes',
      'errorIndex',
      'exampleResponses',
      'expectedCompletionRate',
      'expectedTimeOnTask',
      'expansionGuidelines',
      'extractabilityTier',
      'extraPracticeNotes',
      'forbiddenPatterns',
      'grammarFocus',
      'groupId',
      'groupName',
      'ingestPayload',
      'ingestSource',
      'instructions',
      'isRequiredToPass',
      'intonationOptions',
      'incorrectSentence',
      'keywordThreshold',
      'keywords',
      'l1InterferenceNotes',
      'lastUpdatedAt',
      'lastUpdatedBy',
      'letterUnits',
      'learningObjectives',
      'lessonId',
      'lines',
      'matchPairs',
      'linkedResources',
      'manualOverrideJson',
      'masteryRule',
      'masteryThreshold',
      'maxAttempts',
      'maxScoreValue',
      'maxWordCount',
      'metadata',
      'minWordCount',
      'minAttemptsBeforeSkip',
      'moduleId',
      'note',
      'notesForTeacherOrAI',
      'orderIndex',
      'ownerTeam',
      'passRequiredForNext',
      'passingScoreType',
      'passingScoreValue',
      'prerequisiteEdges',
      'prerequisiteModules',
      'prerequisiteNodes',
      'prerequisiteSlices',
      'prerequisites',
      'priorLessons',
      'pronunciationFocus',
      'promptMode',
      'promptText',
      'propsJson',
      'registerTone',
      'registerVariants',
      'remediationGuidance',
      'remediationPaths',
      'requiredScore',
      'retryPolicy',
      'runtimeContractV1',
      'shortSummaryTeacherActivity',
      'shortSummaryTeacherSlide',
      'signatureMetaphors',
      'simplificationGuidelines',
      'skipPolicy',
      'slideId',
      'slug',
      'sourceVersion',
      'styleConstraints',
      'subtitle',
      'sentenceCards',
      'sentenceTokens',
      'sentenceWithGaps',
      'statement',
      'syllableBreakdown',
      'successCriteria',
      'tags',
      'targetedEdges',
      'targetedNodes',
      'targetedSlices',
      'targetLanguage',
      'targetKeywords',
      'targetNodeKeys',
      'targetText',
      'teacherNotes',
      'teacherOverview',
      'telemetryTags',
      'textSubtype',
      'tenseBins',
      'timeExpectationActivity',
      'title',
      'topicCategory',
      'type',
      'version',
      'visibility',
      'vocabularyTheme',
      'word',
      'wordBank'
    ]
  )
)
INSERT INTO public.field_dictionary_component_rules (field_key, component_name, is_present, is_required)
SELECT
  field_key,
  'activity_slides',
  true,
  CASE
    WHEN field_key IN ('slideId', 'slug') THEN true
    ELSE false
  END
FROM activity_slide_default_fields
ON CONFLICT (field_key, component_name) DO UPDATE
SET
  is_present = EXCLUDED.is_present,
  is_required = EXCLUDED.is_required;
